const {test}=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const express=require('express');
const {createAsksStore}=require('../lib/notify/asks');const {createAskReceipts}=require('../lib/notify/ask-receipts');const {createAskAnswerService}=require('../lib/notify/ask-answer-service');const {notifyRoutes}=require('../lib/notify/routes');
const rid='11111111-1111-4111-8111-111111111111';
function setup(t){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'audit-f32-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const asks=createAsksStore({dir});const id=asks.create({question:'q',session:'cell-test'}).ask.id;const filePath=path.join(dir,'receipts.json');let receipts=createAskReceipts({filePath});let pastes=0;const service=()=>createAskAnswerService({asks,receipts,paste:async()=>{pastes++;return true}});return {dir,asks,id,filePath,get receipts(){return receipts},get pastes(){return pastes},service,unknown(){receipts.attempt({peerId:'peer',askId:id,requestId:rid,text:'yes'});receipts=createAskReceipts({filePath})}}}
test('audit receipt exists on disk BEFORE paste; restart blocks local and no retry',async t=>{const u=setup(t);const svc=createAskAnswerService({asks:u.asks,receipts:u.receipts,paste:async()=>{const disk=JSON.parse(fs.readFileSync(u.filePath));assert.equal(Object.values(disk.attempts)[0].state,'pending');return true}});await svc.answerFederated({askId:u.id,text:'yes',peerId:'peer',requestId:rid});const v=setup(t);v.unknown();const r=await v.service().answerLocal({askId:v.id,text:'again'});assert.equal(r.code,409);assert.equal(v.pastes,0)});
test('audit failed initial receipt write prevents paste',async t=>{const u=setup(t);const rename=fs.renameSync;fs.renameSync=(a,b)=>{if(b===u.filePath)throw new Error('audit disk failure');return rename(a,b)};try{await assert.rejects(u.service().answerFederated({askId:u.id,text:'yes',peerId:'peer',requestId:rid}));assert.equal(u.pastes,0)}finally{fs.renameSync=rename}});
test('audit failed reconciliation must KEEP lock until durable receipt',async t=>{const u=setup(t);u.unknown();const rename=fs.renameSync;let threw=false;fs.renameSync=(a,b)=>{if(b===u.filePath)throw new Error('audit disk failure');return rename(a,b)};try{u.receipts.reconcile(u.id,'allow-new-attempt')}catch(e){threw=true}finally{fs.renameSync=rename}const blocked=u.receipts.isBlocked(u.id);const r=await u.service().answerLocal({askId:u.id,text:'again'});console.log('RECONCILE_WRITE_FAILURE',JSON.stringify({threw,blocked,answer:r,pastes:u.pastes}));assert.equal(blocked,true)});
test('audit mark-delivered must forbid new local paste',async t=>{const u=setup(t);u.unknown();u.receipts.reconcile(u.id,'mark-delivered');const r=await u.service().answerLocal({askId:u.id,text:'duplicate'});console.log('MARK_DELIVERED',JSON.stringify({answer:r,pastes:u.pastes}));assert.equal(u.pastes,0)});
test('audit dismiss delivery-unknown must preserve ask',t=>{const u=setup(t);u.unknown();const r=u.service().dismiss(u.id);console.log('UNKNOWN_DISMISS',JSON.stringify({result:r,blocked:u.receipts.isBlocked(u.id),dismissed:u.asks.get(u.id).dismissed}));assert.equal(r.ok,false)});
test('audit claim loser must not leave a pending receipt',async t=>{const u=setup(t);u.asks.claim(u.id);const r=await u.service().answerFederated({askId:u.id,text:'no',peerId:'peer',requestId:rid});assert.equal(r.code,409);const entry=u.receipts.get('peer',u.id,rid);console.log('CLAIM_LOSER',JSON.stringify(entry));assert.equal(entry.state,'failed')});
test('audit reconcile requires CAS and advances revision',async t=>{const u=setup(t);u.unknown();const app=express();app.use('/api',notifyRoutes({cfg:{},asks:u.asks,receipts:u.receipts,answerService:u.service(),paste:async()=>true,notifier:{emitRaw(){}},push:{},sessionExists:()=>true}));const srv=app.listen(0,'127.0.0.1');await new Promise(r=>srv.once('listening',r));t.after(()=>srv.close());const url=`http://127.0.0.1:${srv.address().port}/api/asks/${u.id}/reconcile`;const response=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({decision:'allow-new-attempt'})});console.log('CAS_OMITTED',response.status,await response.text(),'revision',u.asks.get(u.id).revision);assert.equal(response.status,400)});
test('audit relay timeout has no automatic retry and resolves route from store',async t=>{const {createAskRelay}=require('../lib/notify/ask-relay');let calls=0;const relay=createAskRelay({loadStore:()=>({nodeId:'client',nodes:[{nodeId:'owner',direction:'outbound',token:'test',localPort:12345}]}),fetchImpl:async(url,opts)=>{calls++;assert.ok(url.startsWith('http://127.0.0.1:12345/federation/route/'));assert.deepEqual(Object.keys(JSON.parse(opts.body)).sort(),['requestId','text']);throw new Error('transport lost')}});const a=await relay.relayAnswer({ownerId:'owner',askId:'abcd1234',text:'yes'});assert.equal(a.uncertain,true);const b=await relay.relayAnswer({ownerId:'owner',askId:'abcd1234',text:'yes'});assert.equal(b.code,409);await new Promise(r=>setTimeout(r,20));assert.equal(calls,1);console.log('RELAY_TIMEOUT',JSON.stringify({calls,secondCode:b.code,state:relay.state()[0].state}))});
test('audit two concurrent request IDs share one ask claim',async t=>{const u=setup(t);let pasted=0,finish;const svc=createAskAnswerService({asks:u.asks,receipts:u.receipts,paste:()=>{pasted++;return new Promise(r=>finish=r)}});const first=svc.answerFederated({askId:u.id,text:'yes',peerId:'peer',requestId:rid});const second=await svc.answerFederated({askId:u.id,text:'yes',peerId:'peer',requestId:'22222222-2222-4222-8222-222222222222'});assert.equal(second.code,409);assert.equal(pasted,1);finish(true);assert.equal((await first).ok,true);console.log('CONCURRENT_IDS',JSON.stringify({pasted,secondCode:second.code}))});
